config/routes.rb
Rails.application.routes.draw do
  post "/auth/developer/callback", to: "sessions#create"

  resource :session, only: [:create, :destroy]
  resources :events, only: [:index]
  resources :user, only: [] do
    resource :preferences, only: [:create]
  end

  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, :address, :city, :start_time, presence: true
  validates_each :start_time, :end_time, allow_blank: true do |record, attr, value|
    record.errors.add attr, :invalid unless value.is_a?(Time)
  end

  def self.find_by_preference(preference)
    Event.where(city: preference[:city], start_time: preference[:start_times]).
          where("topics @> ?", "{#{preference[:topic]}}")
  end
end

app/models/preference.rb
class Preference < ApplicationRecord
  belongs_to :user

  validates :city, :topic, :start_times, presence: true
  validates_each :start_times, allow_blank: true do |record, attr, value|
    unless value.is_a?(Range) && value.first.is_a?(Time) && value.last.is_a?(Time) && value.first < value.last
      record.errors.add attr, :invalid
    end
  end

  def self.find_by_event(event)
    Preference.where(city: event[:city], topic: event[:topics]).
               where("start_times @> ?::timestamp", event[:start_time])
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
  has_secure_token
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sessions, dependent: :destroy
  has_one :preference, dependent: :destroy

  validates :email, presence: true, format: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\Z/i

  def logged_in?
    Session.where(user: self).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :authenticated?, :current_session, :current_user

  def login(current_session)
    @current_session = current_session
    cookies.encrypted[:session] = session[:token] = current_session.token
  end

  def logout
    current_session.destroy! if current_session
    @current_session = cookies.encrypted[:session] = session[:token] = nil
  end

  def authenticated?
    !current_session.nil?
  end

  def current_user
    current_session.try(:user)
  end

  def current_session
    @current_session ||= session[:token] && Session.eager_load(:user).find_by(token: session[:token])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    if authenticated?
      if @preference = current_preference
        @events = events(Event.find_by_preference(@preference))
      else
        @preference = new_preference
        @events = events(Event.all)
      end
    else
      @events = events(Event.all)
    end
  end

  private
  def current_preference
    current_user.preference && PreferenceDecorator.new(current_user.preference)
  end

  def new_preference
    PreferenceDecorator.new(current_user.build_preference)
  end

  def events(events)
    events.map {|e| EventDecorator.new(e)}
  end
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  def create
    if authenticated? && current_user.id.to_s == params[:user_id]
      Preferences.create!(current_user, params[:preference]) rescue nil
    end
    redirect_to events_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :create

  def create
    logout
    user = User.find_or_create_by(user_params.slice(:email))
    if user.persisted?
      login(Session.create!(user: user))
    else
      flash[:authentication_error] = {
        class: "danger",
        message: "Failed to authenticate, #{user.errors.full_messages.join(", ")}"
      }
    end
    redirect_to root_path
  end

  def destroy
    logout
    redirect_to root_path
  end

  protected
  def user_params
    ActionController::Parameters.new(request.env['omniauth.auth']['info']).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_event.html.haml
.panel.panel-default
  .panel-body
    %p
      #{event.title} at #{event.address} in #{event.city}
      from #{event.start_time}
      -if event.end_time
        until #{event.end_time}
      about #{event.topics.join(", ")}

app/views/events/index.html.haml
.container
  %h3 Events
  - if @preference
    .row
      .col-md-12
        .well.well-sm
          = form_tag(user_preferences_path(@preference.user), method: :post) do
            %label{for: "city"} City
            %input{type: "text", name: "preference[city]", value: @preference.city, required: true}
            %label{for: "topic"} Topic
            %input{type: "text", name: "preference[topic]", value: @preference.topic, required: true}
            %label{for: "start_times_from"} Starts between
            %input{type: "datetime-local", name: "preference[start_times_from]", value: @preference.start_times_from, required: true}
            %label{for: "start_times_to"} and
            %input{type: "datetime-local", name: "preference[start_times_to]", value: @preference.start_times_to, required: true}
            %input{type: "submit", value: "filter"}

  .row
    .col-md-12.events
      = render @events

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type" }
    %title Meetup
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-default{ role: 'navigation' }
      .container
        .navbar-header
          %a.navbar-brand{ href: root_path } Meetup
        - if authenticated?
          %p.navbar-text.navbar-right
            Welcome back,
            %span= current_user.email
            = link_to session_path, method: :delete do
              Log out
        - else
          %a.navbar-right.btn.navbar-btn{ href: '/auth/developer' }
            Log in to filter events by preference
    .container
      .row
        .col-md-12
          - flash.each do |_, item|
            .alert{ class: ["alert-#{item["class"]}"] }= item["message"]

    = yield